title: Pedro Guedes

description: "A personal portfolio for the designer Pedro Guedes"

baseurl: ""

projects:
  - title: "Projeto 1"
    subtitle: "Subtitulo 1"
    description: "Descrição 1"
    background-color: "#F76161"
    image: "https://lh3.googleusercontent.com/MMue08byixTw74ST_VkNQDUUJBgVEbjNHDYLhIuHmYhMIMJIp3KjVlnhhqZQOZUtNt8=h900-rw"
    info-font-color: "#fff"
    info-title-font: "'Montserrat', sans-serif;"
    info-subtitle-and-description-font: "'Halant', serif;"
    button-color: "#3B7590"
    url-text: "VIEW ON BEHANCE"
    button-font-color: "#fff"
    button-font: "'Montserrat', sans-serif;"
    url: "http://www.behance.net"
  - title: "Projeto 2"
    subtitle: "Subtitlo 2"
    description: "Descrição 2"
    background-color: "#FF00FF"
    image: "https://lh3.googleusercontent.com/foFmwvVGIwWWXJIukN7png18lFjFgbw3K7BqIm8G-jsFgSTVtkCa-dDkFApUzbvzIvbe=h900-rw"
    info-font-color: "#fff"
    info-title-font: "'Montserrat', sans-serif;"
    info-subtitle-and-description-font: "'Halant', serif;"
    button-color: "#3B7590"
    url-text: "VIEW ON BEHANCE"
    button-font-color: "#fff"
    button-font: "'Montserrat', sans-serif;"
    url: "http://www.behance.net"
