title: Pedro Guedes

baseurl: ""

projects:
  - title: "Usisaúde"
    subtitle: "iOS App UI"
    description: "I worked on a new wordpress theme for autondify.com. A job board theme with a heavy focus on video resumes, available for purchase shortly."
    background-color: "#F76161"
    image: ""
    info-font-color: "#fff"
    info-title-font: "'Montserrat', sans-serif;"
    info-subtitle-and-description-font: "'Halant', serif;"
    button-color: "#3B7590"
    url-text: "VIEW ON BEHANCE"
    button-font-color: "#fff"
    button-font: "'Montserrat', sans-serif;"
    url: "http://www.behance.net"
